### ISSUE TITLE
say.js export does not support platofrm linux

### ISSUE THREAD

**Issue by rohan061** [Marak/say.js#57] opened 2017-06-01 06:56 UTC
I am getting this error 

say.js export does not support platofrm linux

```js
var say = require('say');

 
var filename = "myaudio.wav"

say.export("I'm sorry, Dave.", 'Cellos', 0.75, filename, function(err) {
    if (err) {
        return console.error(err);
    }

    console.log('Text has been saved to ${filename}');
});
```

**Comment by tlhunter** [comment] 2017-06-12 04:51
Duplicate of #51

**Closed by tlhunter** 2017-06-12 04:51 UTC
