### ISSUE TITLE
Would you please to support say.export to a wav file on Linux?

### ISSUE THREAD

**Issue by idoor88** [Marak/say.js#104] opened 2020-06-03 14:38 UTC
Currently the library does not support linux for say.export() to a file, it has been for years to be requested feature for many people, but it is still not implemented. it is a hot feature for the library to be useful on Linux.
Thanks

**Comment by idoor88** [comment] 2020-06-03 14:42
Currently the library does not support linux for say.export() to a file, it has been for years to be requested feature for many people, but it is still not implemented. it is a hot feature for the library to be useful on Linux.
Thanks

**Comment by tlhunter** [comment] 2020-06-05 00:07
PRs welcome.

Duplicate of #20.

**Closed as completed by tlhunter** 2020-06-05 00:07 UTC

**Comment by idoor88** [comment] 2020-06-06 04:58
Sorry, What do you mean by saying PRs welcome, I am writing this issue to ask for this feature, why do not you create a PR and let somebody work on the feature?
Thanks

**Comment by tlhunter** [comment] 2020-06-08 19:33
> why do not you create a PR

Because working on this module isn't my job. It isn't anybody's job. It's just a side project, one that I don't use anymore. I suspect that even @Marak, the original module author, doesn't use the project anymore. I don't even think it's fair to call it "our" side project. It's the JavaScript ecosystem's side project. Everybody has free access to the code and everybody is encouraged, yourself included, to contribute features.

Marak and I are merely gatekeepers at this point. We'll happily shepherd in features from the community, and occasionally add features ourselves, but there's literally zero benefit for us to write code like this on demand. We don't get paid to work on it. Often it's people who come by asking for features for free who are the ones that actually profit from the work others put into these modules.

As for why I closed this issue, it is a duplicate of an existing issue (#20) also asking for this feature to be added.
