### ISSUE TITLE
export on linux not work

### ISSUE THREAD

**Issue by stefanocudini** [Marak/say.js#51] opened 2017-03-01 23:46 UTC
in my debian with node v6.10.0
"say.js export does not support platform linux"

**Comment by tlhunter** [comment] 2017-05-30 07:05
That's really weird. We've supported Linux for as long as I've been maintaining the project. Here you can see we specifically accept it:

https://github.com/Marak/say.js/blob/80eed6a648aa813cbd8155edb47c1e1ea4bca37c/index.js#L50-L68

Which version of this library are you using? Latest?

**Comment by stefanocudini** [comment] 2017-05-30 09:13
yes I installed using *npm install say*

**Comment by tlhunter** [comment] 2017-06-12 04:58
Sorry, I didn't properly read your ticket, you're specifically asking about exporting on Linux. This is a feature we haven't added yet. See #20.

We know how to do it, we just haven't implemented it yet (see last comment in #20). Feel free to create a PR if you'd like to see this feature added.

**Comment by tlhunter** [comment] 2017-11-06 00:40
Closing as duplicate of #20.

**Closed by tlhunter** 2017-11-06 00:40 UTC
Labels: Feature Request, OS:Linux
